name:    FileHandlerYesod
version: "0.1.0"

dependencies:
- base
- yesod
- yesod-core
- classy-prelude >=1.5 && <1.6
- classy-prelude-conduit >=1.5 && <1.6
- classy-prelude-yesod >=1.5 && <1.6
- http-types
- bytestring
- aeson
- wai
- wai-extra
- warp
- text
- req
- zip
- temporary
- case-insensitive
- resourcet
- mtl
- directory
- filepath
- yaml
- file-embed



# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  FileHandlerYesod:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FileHandlerYesod
