name:                Filehandler
version:             0.1.0.0
github:              "githubuser/Filehandler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Filehandler#readme>

dependencies:
- base >= 4.7 && < 5
- req
- shakespeare
- wai
- wai-app-static
- wai-extra
- warp
- network
- text
- aeson
- filepath
- http-types
- bytestring
- directory
- text
- case-insensitive
- blaze-html


library:
  source-dirs: src

executables:
  Filehandler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Filehandler

tests:
  Filehandler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Filehandler
