appProfile: "_env:APP_PROFILE:prod"

fileSystemServiceSettings:
  url: "_env:FILESYSTEMSERVICE_URL:localhost"
  port: "_env:FILESYSTEMSERVICE_PORT:8080"

encryptionPassword: "_env:ENCRYPTION_PASSWORD:changeThis"

database:
  user: "yesodMongoTemplate"
  password: "yesodMongoTemplate"
  host: "localhost"
  database: "yesodMongoTemplate"
  connections: 10
