name: Stable Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Build_Docker_Image_on_Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Project
        uses: actions/checkout@v3
      -
        name: Build Filehandler
        run: |
          stack build
          
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      -
        name: Generate Image Tag from Git Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Build and push
        run: |
          VERSION=${{ steps.vars.outputs.tag }}
          BINLOCATION=$(stack path --local-install-root)
          BINLOCATION=$(realpath --relative-to=. $BINLOCATION)
          docker build -t filefighter/filehandler:$VERSION -t filefighter/filehandler:stable . --build-arg BINLOCATION=$BINLOCATION
          docker push filefighter/filehandler:$VERSION
          docker push filefighter/filehandler:stable